### ISSUE TITLE
Add Webcam

### ISSUE THREAD

**Issue by MyIgel** [optikfluffel/34c3.info#2]
ITs located [here](http://livecam.leipziger-messe.de/) or direct [here](http://195.16.83.254/viewer/live/de/live.html)

**Comment by optikfluffel** [comment]
I‘m not sure about this one. The first link doesn‘t work and the second doesn‘t show anything „useful“. Why do you think this should be in here? Maybe you could put it into the [Wiki](https://events.ccc.de/congress/2017/wiki/index.php/Main_Page)?

**Comment by MyIgel** [comment]
It works for me, it is an overview webcam that films the whole congress and is contrallable

**Comment by optikfluffel** [comment]
I probably ran into:
> maximal 20 Nutzer gleichzeitig

I'm a little sorry but I still don't think this belongs onto [34c3.info](http://34c3.info) because it's a nice gimmick, but doesn't help anybody to have a better/nicer/easier congress.

I will close this for now and hope you're not irritated by this. Thanks anyway 💕
